name: Build Project

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Android
        run: |
          cd PeedrocaApp
          nuget restore
          cd PeedrocaApp.Android
          msbuild PeedrocaApp.Android.csproj
