name: Build Project

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
      
      - name: Restore Solution
        run: dotnet restore PeedrocaApp/PeedrocaApp.sln
        
      - name: Compile Solution
        run: dotnet build PeedrocaApp/PeedrocaApp.sln
