name: Build Project

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Restore Solution
        run: dotnet restore PeedrocaApp/PeedrocaApp.sln
        
      - name: Compile Solution
        run: dotnet build PeedrocaApp/PeedrocaApp.sln
